import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import "./globals.css";

const mulish = Mulish({
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.className} dark antialiased`}>
        <SessionProvider>{children}</SessionProvider>{" "}
        {/* Envolvendo o conteúdo com o SessionProvider */}
      </body>
    </html>
  );
}
